// Generated by LiveScript 1.4.0
var Base_Controller, Details_Controller, Education_Controller, Events_Controller, Awards_Controller, Skills_Controller, Experience_Controller;
$(function(){
  $('.projects').on('click', 'h6 i', function(){
    var q;
    q = $(this).toggleClass('fa-plus-square-o fa-minus-square-o').parent().siblings('.cnt').slideToggle().end().parent().siblings().find('.fa-minus-square-o').toggleClass('fa-plus-square-o fa-minus-square-o').parent().siblings('.cnt').slideToggle();
    console.log(q);
  });
});
Base_Controller = function($scope){
  $scope.range = function(n){
    var i$, i, results$ = [];
    for (i$ = 1; i$ <= n; ++i$) {
      i = i$;
      results$.push(i);
    }
    return results$;
  };
};
Details_Controller = function($scope){
  $scope.data = DATA.details;
};
Education_Controller = function($scope){
  $scope.data = DATA.education;
};
Events_Controller = function($scope){
  $scope.data = DATA.events;
};
Awards_Controller = function($scope){
  $scope.data = DATA.awards;
};
Skills_Controller = function($scope){
  $scope.data = DATA.skills;
};
Experience_Controller = function($scope){
  $scope.data = DATA.experience;
};